security:
    encoders:
        AppBundle\Entity\Client: 
            algorithm: plaintext
            ignore_case: false
        AppBundle\Entity\Restaurateur: 
            algorithm: plaintext
            ignore_case: false
        AppBundle\Entity\Entrepreneur: 
            algorithm: plaintext
            ignore_case: false
        AppBundle\Entity\Livreur: 
            algorithm: plaintext
            ignore_case: false

    role_hierarchy:
        ROLE_REST:     ROLE_USER
        ROLE_ENT:       ROLE_REST
        ROLE_ADMIN:   ROLE_ENT
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [user_db, rest_db, ent_db, liv_db]
        user_db:
            entity: {class: AppBundle\Entity\Client, property: courriel}
        rest_db:
            entity: {class: AppBundle\Entity\Restaurateur, property: courriel}
        ent_db:
            entity: {class: AppBundle\Entity\Entrepreneur, property: courriel}
        liv_db:
            entity: {class: AppBundle\Entity\Livreur, property: courriel}

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                failure_path: /
            logout:
                path: /logout
                target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login$
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }